server:
  port: 8700
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aabb?createDatabaseIfNotExist=true
    username: root
    password: Mysql@4811
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:      ddl-auto: update
      
  application:    name: user-service

eureka:  instance:    hostname: localhost
        